const { DataTypes } = require('sequelize');
const sequelize = require('../config/db'); // Adjust if your sequelize config is in a different file

const StudentApplicationDraft = sequelize.define('student_application_draft', {
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  khidmat_current: DataTypes.STRING,
  khidmat_intent: DataTypes.STRING,
  studied_kalemat_daim: DataTypes.ENUM('Yes', 'No'),
  memorized_names: DataTypes.ENUM('Yes', 'No'),
  offers_sila_vajebaat: DataTypes.ENUM('Yes', 'No'),
  attended_misaq_majlis: DataTypes.ENUM('Yes', 'No'),
  moharramaat_survey: DataTypes.ENUM('Yes', 'No'),
  shaadi_status: DataTypes.ENUM('Yes', 'No'),
  spouse_name: DataTypes.STRING,
  ashara_attendance: DataTypes.STRING,
  ziarat_raudat_tahera: DataTypes.ENUM('Yes', 'No'),
  namaz_daily: DataTypes.STRING,
  father_name: DataTypes.STRING,
  father_cnic: DataTypes.STRING,
  mother_name: DataTypes.STRING,
  mother_cnic: DataTypes.STRING,
  house_title: DataTypes.STRING,
  area: DataTypes.STRING,
  neighborhood: DataTypes.STRING,
  drinking_water: DataTypes.STRING,
  sanitation_bathroom: DataTypes.ENUM('Yes', 'No'),
  wallFlooring: DataTypes.ENUM('Yes', 'No'),
  leakage: DataTypes.ENUM('Yes', 'No'),
  personalBank: DataTypes.ENUM('Yes', 'No'),
  taking_fmb: DataTypes.STRING,
  fmb_quantity_sufficient: DataTypes.STRING,
  height: DataTypes.DECIMAL(5, 2),
  weight: DataTypes.DECIMAL(5, 2),
  physically_mentally_challenged: DataTypes.ENUM('Yes', 'No'),
  child_death_past_5yrs: DataTypes.ENUM('Yes', 'No'),
  child_death_cause: DataTypes.STRING,
  vaccination_status: DataTypes.ENUM('Yes', 'No'),
  chronic_illness: DataTypes.ENUM('Yes', 'No'),
  incomeType: DataTypes.STRING,
  familyMemberName: DataTypes.STRING,
  studentPartTimeIncome: DataTypes.DECIMAL(10, 2),
  family_member_working: DataTypes.ENUM('Yes', 'No'),
  working_details: DataTypes.TEXT,
  family_member_disability: DataTypes.ENUM('Yes', 'No'),
  disability_details: DataTypes.TEXT,
  wajebaat_expenses: DataTypes.DECIMAL(10, 2),
  niyaz_expenses: DataTypes.DECIMAL(10, 2),
  sabeel_expenses: DataTypes.DECIMAL(10, 2),
  zyarat_expenses: DataTypes.DECIMAL(10, 2),
  ashara_expenses: DataTypes.DECIMAL(10, 2),
  qardanhasana: DataTypes.DECIMAL(10, 2),
  other_deeni_expenses: DataTypes.DECIMAL(10, 2),
  groceries_supplies: DataTypes.DECIMAL(10, 2),
  dineout_expense: DataTypes.DECIMAL(10, 2),
  essential_expense: DataTypes.DECIMAL(10, 2),
  doctor_expenses: DataTypes.DECIMAL(10, 2),
  dental_expenses: DataTypes.DECIMAL(10, 2),
  glass_expenses: DataTypes.DECIMAL(10, 2),
  meds_expenses: DataTypes.DECIMAL(10, 2),
  vacation_expenses: DataTypes.DECIMAL(10, 2),
  rent_expense: DataTypes.DECIMAL(10, 2),
  maintenance_expense: DataTypes.DECIMAL(10, 2),
  gas_expense: DataTypes.DECIMAL(10, 2),
  electricity_expense: DataTypes.DECIMAL(10, 2),
  mobile_expense: DataTypes.DECIMAL(10, 2),
  water_expense: DataTypes.DECIMAL(10, 2),
  cable_expense: DataTypes.DECIMAL(10, 2),
  internet_expense: DataTypes.DECIMAL(10, 2),
  clothing_expense: DataTypes.DECIMAL(10, 2),
  appliances_expense: DataTypes.DECIMAL(10, 2),
  other_expenses: DataTypes.DECIMAL(10, 2),
  property_assets: DataTypes.DECIMAL(10, 2),
  jewelry_Assets: DataTypes.DECIMAL(10, 2),
  transport_assets: DataTypes.DECIMAL(10, 2),
  other_assets: DataTypes.DECIMAL(10, 2),
  assets_base64: DataTypes.TEXT('long'),
  education_expenses_base64: DataTypes.TEXT('long'),
  dependents_base64: DataTypes.TEXT('long'),
  travelling_expense_base64: DataTypes.TEXT('long'),
  business_assets_base64: DataTypes.TEXT('long'),
  qh_liability_base64: DataTypes.TEXT('long'),
  enayat_liability_base64: DataTypes.TEXT('long'),
}, {
  timestamps: false,
  tableName: 'student_application_draft',
});

module.exports = StudentApplicationDraft;